# Generated by Django 4.2.2 on 2025-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000198969C7920>', max_length=200),
        ),
    ]
