# Generated by Django 4.2.2 on 2025-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_alter_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001891C65E520>', max_length=200),
        ),
    ]
