# Generated by Django 4.2.2 on 2025-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='versioning',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
