# Generated by Django 4.2.2 on 2025-04-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stock_product_versioning'),
    ]

    operations = [
    ]
