# Generated by Django 4.2.2 on 2025-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_trigger_stock_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='versioning',
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
